In [1]:
import numpy as np

Numpy Reference Doc
https://numpy.org/doc/stable/reference/index.html

In [2]:
np_array =np.array("hello")
print(type(np_array))

<class 'numpy.ndarray'>


In [3]:
np_array

array('hello', dtype='<U5')

In [4]:
# Returns evenly spaced values
np_array = np.arange(0,10)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Returns evenly spaced values, but by 0.5
np_array = np.arange(0,10, 0.5)
np_array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [6]:
# In summary, use arange when you need to specify a start, stop, and step size, and use linspace when you need a specific number of points evenly spaced within an interval.
# But both can do the same thing, its just preference
np_array = np.linspace(10,20,11)
print(np_array)

# Iterating over the array
for i in np_array:
    print(i)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0


In [7]:
np_matrix_ones = np.ones([3,5])          # 3 row and 5 column matrix with all ones
np_matrix_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np_matrix_zeroes = np.zeros([2,4])          # 2 row and 4 column matrix with all zeroes
np_matrix_zeroes



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np_matrix_zeroes = np.zeros([2,4], dtype=int)          # 2 row and 4 column matrix with all zeroes and type integer
np_matrix_zeroes

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
#  np.eye returns only the square matrix
np_idendity_matrix = np.eye(5)      # idendity Matrix of 5X5. It has all diagonals as one.
np_idendity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
arr = np.arange(0,10)                    # Reshaped a linear list of data to 2X5 Matrix
arr_reshape = arr.reshape(2,5)
print(arr_reshape)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
## Trigonometric functions
print(np.sin(0.523599))           # 0.523599 radian is 30 degree
print(np.cos(0.523599))
print(np.tan(0.523599))
print(np.pi/2)

0.5000001943375613
0.8660252915835662
0.5773505683919328
1.5707963267948966


In [13]:
print(np.exp(2))         # this is equal to (e**2)       
print(np.log(2))         # Log of 2 with base e.
print(np.log10(100))     # Log 100 with base 2
#  The number e, also known as Euler's number, is a mathematical constant approximately equal to 2.71828 
#  that can be characterized in many ways. It is the base ...
array = np.array([2,4,6])
print(np.exp(array))           # This will print e**2, e**4, e**6

7.38905609893065
0.6931471805599453
2.0
[  7.3890561   54.59815003 403.42879349]


In [14]:
# Normal Matrix multiplication and addition are performed column wise

arr1 = np.arange(1,11).reshape(2,5)
print(arr1)
arr2 = np.arange(12,22).reshape(2,5)
print(arr2)
print(arr1+arr2)         # Operations are columnwise of matrix
print(arr1*arr2)         # Operations are columnwise of matrix
print(arr1-arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[12 13 14 15 16]
 [17 18 19 20 21]]
[[13 15 17 19 21]
 [23 25 27 29 31]]
[[ 12  26  42  60  80]
 [102 126 152 180 210]]
[[-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]]


In [15]:
##### Linear algebra Matrix multiplication

arr1 = np.arange(1,11).reshape(2,5)
print(arr1)
arr2 = np.arange(12,27).reshape(5,3)
print(arr2)
print("---------------------")
print(arr1 @ arr2)                 ## This will do the actual matrix dot mult

# Transpose a matrix. Flip rows to columns

arr1 = np.arange(0,12).reshape(3,4)
print(arr1)
print(np.transpose(arr1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]]
---------------------
[[300 315 330]
 [750 790 830]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [16]:
# We can do transpose in another way as
print(arr1.T)  ## Shirt hand notation of Matrix transpose

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [17]:
# min and Maximum in a numpy
arr1 = np.arange(0,12).reshape(3,4)
print(arr1)
print(np.min(arr1))
print(np.max(arr1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
11


In [18]:
# Random Value generations
print(np.random.rand(5)) # Create a single dimensional array of 5 elements with random values between 0 - 1 
print(np.random.rand(5,5))  # Create a 5X5 matrix of random number with values from 0 - 1

# randn creates a random number whose samples are drawn from normal distribution(Whose mean is 0 and standard deviation as 1)
arr1 = np.random.randn(5)
arr2 = np.random.randn(5,5) # Same as above but genarated 5X5 
print(arr1)
print(arr2)
print(np.mean(arr1))            #   Mean would be closer to 0
print(np.std(arr1))             #   Standard deviation would be 1

# Creates a 10 random number between 1 and 5(not including 5)
print(np.random.randint(1, 5, 10))  # low, high, number of random numbers.


[0.6093368  0.19358371 0.27049078 0.56950041 0.32521272]
[[0.39301306 0.85951581 0.09496741 0.22880967 0.34782071]
 [0.99136077 0.09589797 0.3044111  0.14345869 0.07967793]
 [0.89794665 0.4887547  0.78597658 0.12500658 0.17539715]
 [0.96030815 0.61911287 0.91712319 0.32166589 0.27219541]
 [0.1842632  0.25214456 0.50970878 0.57745852 0.8072346 ]]
[-0.10041548 -2.09097659  0.27802111  0.08071732 -0.59944719]
[[-1.91198408e+00 -4.02417445e-01  7.94692564e-01 -6.36338301e-01
  -1.28363193e+00]
 [ 2.02803525e+00 -1.03006329e+00  4.18219937e-02  1.97981469e-01
  -7.38805277e-01]
 [ 6.69505210e-04  9.09195139e-01  1.07274881e+00 -1.59120085e+00
  -1.58618071e+00]
 [ 1.65879183e+00  8.06304675e-01 -1.65225670e+00  6.69146516e-01
   1.83749944e-01]
 [ 3.41293399e-01 -1.05824847e+00 -4.95250809e-01  6.16262614e-01
   2.92900034e-01]]
-0.48642016671155003
0.8535093973146061
[2 4 4 2 1 1 4 4 1 1]


In [19]:
# Accessing elements from the np array

print(np.arange(3, 10, 2))      # Range of numbers from 3-10 and step size of 2. The indices are 3,5,7,9
indices = np.arange(3, 10, 2)   # The indices are 3,5,7,9 
# Now let suppose we have a numpy array
arr1 = np.random.randn(50)
print(arr1[indices]) # Since indices are 3,5,7,9 so from arr1 get the values located at indices 3,5,7,9


[3 5 7 9]
[-0.67935441 -0.94699513 -0.03556146 -1.55845546]


In [20]:
# Choosing the elements of array based on certain condition
arr = np.random.randn(50)
print(arr)
# Now let suppose we want only those elemnts which are greater than 0 in array arr then we can say
print(arr[arr>0])        # Filter data which are greater than Zero
# Similarly for numbers less than zero we can say
print(arr[arr<0])       # Filter data which are lesser than Zero  

[-2.08260479 -1.73761234 -0.31644821 -0.34564064 -0.86613989  0.67590043
  0.71156837 -1.03157006  0.72296005  0.2681038  -0.16697987  1.22753761
 -2.00816139  0.92528609 -0.54880052  0.83812129  1.02543434 -1.28264228
 -0.58581246 -1.19002016  0.18388063  0.32535094  0.42201131  0.78312609
  0.33903895  0.78704345 -1.76829494  0.6717475   1.44971956 -0.5436613
 -1.186082    0.94335984  0.72752433 -0.76555821  0.19080179 -1.09537862
  1.06337208 -0.54248374  0.04731232  0.55062739 -1.90574025 -0.0959779
  1.09353056 -0.14916429 -0.71785396  1.40694036 -0.91402769 -0.08099708
  2.21688896 -0.80086061]
[0.67590043 0.71156837 0.72296005 0.2681038  1.22753761 0.92528609
 0.83812129 1.02543434 0.18388063 0.32535094 0.42201131 0.78312609
 0.33903895 0.78704345 0.6717475  1.44971956 0.94335984 0.72752433
 0.19080179 1.06337208 0.04731232 0.55062739 1.09353056 1.40694036
 2.21688896]
[-2.08260479 -1.73761234 -0.31644821 -0.34564064 -0.86613989 -1.03157006
 -0.16697987 -2.00816139 -0.54880052 -

In [21]:
# Below code would replace all elements greater than 6 with 2, remainder of the element in array will remain as it is
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


In [22]:
arr = np.random.randint(0, 50, 20)    # Low, high, number of random number
print(arr)
new_arr = arr.reshape((5,4))
print(new_arr)

# Now in order to access a specific element let suppose  2nd row and 3rd element we can say
print(new_arr[1,2])          # We can access in this way the element at indices 1 and 2 and also as shotcut in below
print(new_arr[1][2])    

print(new_arr[1])           # Print all the elements of row index 1

new_arr[1:3, 0:2] = -100       # Changes the elements from "row 1 till 2(Not including 3)" and from column 0 till 
print(new_arr)

new_arr[:] = 0
print(new_arr)         # Change all rows and columns to 0

[47 32 24 33 38 13 40 24 17  2 40 34  5 30 28 19 14 11 10 38]
[[47 32 24 33]
 [38 13 40 24]
 [17  2 40 34]
 [ 5 30 28 19]
 [14 11 10 38]]
40
40
[38 13 40 24]
[[  47   32   24   33]
 [-100 -100   40   24]
 [-100 -100   40   34]
 [   5   30   28   19]
 [  14   11   10   38]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [23]:
# Copy method to create a new copy of array instead of reference to original array

arr = np.random.randint(0, 50, 20).reshape(5,4)    # Low, high, number of random number
print(arr)
sub_array = arr[2,0:3]
print(sub_array)
sub_array[:] = 0 
print(sub_array)
print(arr)            # Note original array also got modified with zeroes for 3rd row and 0-3 columns


[[18 45 35 20]
 [ 0 22  0 37]
 [ 9 42 43 16]
 [ 9 14 35 29]
 [32 27  2  2]]
[ 9 42 43]
[0 0 0]
[[18 45 35 20]
 [ 0 22  0 37]
 [ 0  0  0 16]
 [ 9 14 35 29]
 [32 27  2  2]]


In [24]:
# If we dont want reference or tie up between original array and new subarray we can use copy method

arr = np.random.randint(0, 50, 20).reshape(5,4)    # Low, high, number of random number
sub_array = arr[2,0:3].copy()
print(sub_array)
sub_array[:] = 0 
print(sub_array)
print(arr)            # Note original array also got modified with zeroes for 3rd row and 0-3 columns


[25 41 34]
[0 0 0]
[[24 26 22 21]
 [46 12 21 21]
 [25 41 34 31]
 [43 34 10  9]
 [41  0  1 20]]


In [25]:
##########################################################
# saving the np data
arr = np.arange(15,25).reshape(5,2)
print(arr)
np.save("np_saved_data", arr)
loaded_arr = np.load("./np_saved_data.npy")
print(loaded_arr)

[[15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
[[15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]


In [26]:
# saving multiple data in one file using np.savez
# and loading multiple arrays back from file
arr1 = np.arange(15,25).reshape(5,2) 
arr2 = np.arange(25,35).reshape(2,5) 
np.savez("np_saved_ez", arr1, arr2)
loaded_array = np.load("np_saved_ez.npz")
arr_1 = np.load("np_saved_ez.npz")
print(loaded_array["arr_0"])
print(loaded_array["arr_1"])

[[15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
[[25 26 27 28 29]
 [30 31 32 33 34]]


In [27]:
# Saving and loading the numpy array in a textfile and loading it back
arr1 = np.arange(15,25, dtype = int).reshape(5,2) 
np.savetxt("np_save.txt", arr1, delimiter=",")
arr1 = np.loadtxt("np_save.txt", delimiter = ",", dtype=int)
print(arr1)

[[15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]


/var/folders/xv/mx7fpfds1nb2h2ps9fxzf1180000gn/T/ipykernel_67323/3594553886.py:4: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  arr1 = np.loadtxt("np_save.txt", delimiter = ",", dtype=int)


In [28]:

a1 = np.arange(10)
print(a1) 
print(a1.shape)

print('------------')
## Provide the step size of 2
a2 = np.arange(0,11,2)      ##2,2,4,6,8,10
print(a2) 
print(a2.shape)             ##

a3 = np.zeros(5)
print(a3)
print(a3.shape)


print('---------------------')
a4 = np.zeros((5,4))    # Two dimensional array with 5 rows and 4 columns
print(a4)
print(a4.shape)


print('---------------------')
a5 = np.full((5,4),8)    # Two dimensional array with 5 rows and 4 columns and filled with all 8
print(a5)
print(a5.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
------------
[ 0  2  4  6  8 10]
(6,)
[0. 0. 0. 0. 0.]
(5,)
---------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(5, 4)
---------------------
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
(5, 4)


In [29]:

###Identity Matrix
print("-------------------")
a6 = np.eye(4)  # Creates an identity matrix of 4X4 with all diagoanal element as 1
print(a6)


-------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:

## Array filled with random number
print("-------------------")
a7 = np.random.random((2,4))
print(a7)

# Create a numpy array from python list
list1 = [1,2,3,4,5]
r1 = np.array(list1)
print(r1)


## Creating and accessing a two dimensional array
print('------------------')
#a4 = np.zeros((5,4))    # Two dimensional array with 5 rows and 4 columns

-------------------
[[0.26010005 0.78905584 0.37305307 0.98139327]
 [0.08199725 0.18248645 0.31163658 0.55661461]]
[1 2 3 4 5]
------------------


In [31]:
a4 = np.random.random((5,4) )    # Two dimensional array with 5 rows and 4 columns

print(a4)
print(a4.shape)

print('------------------')
for x in range(len(a4)):
    print(a4[x])

print(a4[2][0])
print(a4[2][1])

[[0.71425724 0.56043085 0.45165236 0.8289462 ]
 [0.41580187 0.71636254 0.65496841 0.31098382]
 [0.46817073 0.1715714  0.55556693 0.50547005]
 [0.15201004 0.34228324 0.24780515 0.92330202]
 [0.67837275 0.71261094 0.31305066 0.07429533]]
(5, 4)
------------------
[0.71425724 0.56043085 0.45165236 0.8289462 ]
[0.41580187 0.71636254 0.65496841 0.31098382]
[0.46817073 0.1715714  0.55556693 0.50547005]
[0.15201004 0.34228324 0.24780515 0.92330202]
[0.67837275 0.71261094 0.31305066 0.07429533]
0.46817072720704944
0.17157139795151


In [32]:
### print odd number using boolen indexing in numpy
import numpy as np
import time

a = np.arange(10)
print(a%2 == 1)
odd_num = a[a%2 == 1]
print(odd_num)


def p(*args):
    print("############################")
    for arg in args:
        print(arg)

print(np.sin(0.523599))

print(np.sin(np.array([30,60,120,180])))

[False  True False  True False  True False  True False  True]
[1 3 5 7 9]
0.5000001943375613
[-0.98803162 -0.30481062  0.58061118 -0.80115264]


In [33]:
x1 = np.array([1,2,3,4])
print(x1[1])

2


In [34]:
x2 = np.array([4,3,1,2], dtype=np.int32)
print(x1.dtype)
print(x2.dtype)


int64
int32


In [35]:
print(x1*x2)  # Array of element wise multiplication  1*4, 2*3, 3*1, 4*2


[4 6 3 8]


In [36]:
# Create a random element in numpy

r1= np.random.rand(1_000_000)
r2= np.random.rand(1_000_000)

start = time.time()
x = r1 * r2
end = time.time()
print(end-start)


0.001085042953491211


In [37]:
x1 = np.array([1,2,3,4])
x2 = np.array([[4],[3],[1],[2]])

print(x1 @ x2) # Scientific dot product of matrix
# 1*4 + 2*3 + 3*1 + 4*2 = 21


[21]


In [38]:
# get a range of array similar to python range
x = np.arange(12)
print(x)            # Get a number from range 0 -12(not including 12)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
# Reshap an array 

x = x.reshape(4,3)          # Shape it to 4 rows and 3 columns
print(x)
print(x.shape)              # Tells the shape of the Matrix, like 4,3 etc

print(x.T)                  # Prints the transformed matrix, ROWs becomes column.

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [40]:
x= np.array([[1,2,3],[5,6,7],[3,6,-1]])
print(x)

# [[ 1  2  3]
#  [ 5  6  7]
#  [ 3  6 -1]]

# If we need to get from second row and third element we can say
print(x[1,2])      # this will print 7

# If we need all element of 3rd row
print(x[2,:])         # This will print 3, 6, -1

# If we all all element of 2nd columns of all row we can say
print(x[:, 1])  # This will print 2, 6, 6


[[ 1  2  3]
 [ 5  6  7]
 [ 3  6 -1]]
7
[ 3  6 -1]
[2 6 6]


In [41]:
# Intialize or fill an array with Another value

x = np.arange(3)
p(x)

x = x[[True, False, True]]
p(x)         # This will print the element where index was true like 0 2 in this case

x =np.array([1,0,-2,5,25,0,-3]) 
p(x[x>=1])       # Gets the lcaotion of the array where it is greater than 1
                # 1,5,25

############################
[0 1 2]
############################
[0 2]
############################
[ 1  5 25]


In [42]:
arr = np.arange(10)
print(arr)
p(arr[(arr>7) |  (arr <2)])        # 0 1 8 9, prints an array 0 1 8 9
                                    # Note we have to provide condition in bracket()

p(arr[~(arr>7)])    # Print everything not greater than 7 [0,1,2,3,4,5,6,7]

[0 1 2 3 4 5 6 7 8 9]
############################
[0 1 8 9]
############################
[0 1 2 3 4 5 6 7]


In [43]:
# Create an array of 10 elements with values filled as 1000

values = np.random.normal(0,10, 1_000)       # Array of 1000 elements with mean of 0 and standard deviation of 10
values[33] = 1038                   
values[832] = -3423
p(values)
p(values.mean())

mask = np.abs(values - values.mean()) > (2* values.std())
print(values[mask])                             # This will give the values of outlier, basically values[33] and values[832]


############################
[-8.23811427e-01 -1.83889629e+01  4.88688150e+00 -2.22971176e+01
 -7.66189664e+00  2.55610587e+00  9.94337707e+00  1.44377159e-01
 -9.42507129e+00 -6.63007607e+00 -2.64155732e+00 -1.79641055e+01
  3.19132293e-01  4.77391877e+00 -5.24019515e+00  7.65396307e+00
  6.00130549e+00 -8.14870193e+00 -8.33668552e+00  1.25084827e+01
 -1.26433313e+01  9.01018596e+00 -2.02766869e+00 -8.70747311e+00
 -2.96004787e+00  4.05800022e+00  8.75307384e+00  2.59570858e+00
  9.05004879e+00  3.79990799e+00 -1.05721178e+00 -8.90836185e-01
 -2.42186226e+00  1.03800000e+03 -8.49411118e+00 -7.14692845e-01
  6.89201226e+00  2.38801207e+01 -1.12743626e+01  9.10307268e+00
  1.00495729e+01  1.39272288e+01  9.07910143e+00 -3.86443449e+00
  6.99576732e+00  7.12769729e+00  7.73276333e+00  1.57593005e+01
  1.32930724e+01 -1.12911541e+00 -7.10989195e+00 -1.02453945e+01
  9.72231421e+00  2.23796141e+00  5.13658690e+00 -1.28252376e+01
 -1.88445713e+01  3.57760115e-02  4.35673763e+00 -8.74839115e

In [44]:
arr = np.arange(3)
p(arr)
p(arr+4)       # Added the 4 to each of the elements



############################
[0 1 2]
############################
[4 5 6]


In [45]:
# Broadcasting 1

mat = np.arange(9).reshape((3,3))
vec = np.arange(3)
p(mat)
p(vec)
p(mat+vec)      # Added the vector to every row

############################
[[0 1 2]
 [3 4 5]
 [6 7 8]]
############################
[0 1 2]
############################
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [46]:
# Broadcasting 2

v1 = np.arange(3)
v2 = np.arange(3).reshape((3,1))
p(v1)
p(v2)
p(v1+v2)             ## Added the vector v1 to each row of v2

############################
[0 1 2]
############################
[[0]
 [1]
 [2]]
############################
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [47]:
v = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]
              ])
p("Original vector is ", v)
p(v.T)    # T is for trnaspose Matrix, the rows would become the colums

p(v.any())         # This will return true if there is atleast one element in the array which is true

p(v.all())          #v.all will return True if all elements of matrix is true, else it returns false


############################
Original vector is 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
############################
[[0 3 6]
 [1 4 7]
 [2 5 8]]
############################
True
############################
False


In [48]:
v = np.array([[1,1,2],
              [3,4,5],
              ])
p(v.prod())              # Product of all the elements in an array

p(v.sum(axis=1))       # Sum of the rows
p(v.sum(axis=0))       # Sum of the colums



############################
120
############################
[ 4 12]
############################
[4 5 7]


In [49]:
v1 = np.array([[1,1,2],
              [3,4,5],
              ])
v2 = v1.copy()   # Creates a copy of the original array
v2[1,2] = 16
p(v1)
p(v2)


############################
[[1 1 2]
 [3 4 5]]
############################
[[ 1  1  2]
 [ 3  4 16]]


In [50]:
x = np.sin(90)  # This 90 is in radian not degree
p(x)


############################
0.8939966636005579


In [51]:
n = np.arange(-3,3)     # Run the sine function on a vector
print(np.sin(v))


[[ 0.84147098  0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]]


In [52]:
@np.vectorize                 #This method would make the data extend to vector
def relu(n):
    if n<0:
        return 0.0
    return n

p(relu(2))

v1 = np.arange(-3,5)
p(v1)

p(relu(v1))
p(relu(v1)-7)         # This will remove -7 from vector(i.e, each component of the vector)


############################
2
############################
[-3 -2 -1  0  1  2  3  4]
############################
[0. 0. 0. 0. 1. 2. 3. 4.]
############################
[-7. -7. -7. -7. -6. -5. -4. -3.]


In [53]:

#Pearson Correlation

def correlation_coefficient(data1, data2):
  """
  Calculates the correlation coefficient between two lists of data.

  Args:
    data1: The first list of data.
    data2: The second list of data.

  Returns:
    The correlation coefficient between the two lists of data.
  """

  mean1 = np.mean(data1)
  mean2 = np.mean(data2)
  std1 = np.std(data1)
  std2 = np.std(data2)

  covariance = np.sum((data1 - mean1)*(data2 - mean2)) / len(data1)
  correlation = covariance / (std1 * std2)

  return correlation