In [1]:
import numpy as np

Numpy Reference Doc
https://numpy.org/doc/stable/reference/index.html

In [2]:
np_array =np.array("hello")
print(type(np_array))

<class 'numpy.ndarray'>


In [3]:
np_array

array('hello', dtype='<U5')

In [6]:
# Returns evenly spaced values
np_array = np.arange(0,10)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Returns evenly spaced values, but by 0.5
np_array = np.arange(0,10, 0.5)
np_array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [9]:
# In summary, use arange when you need to specify a start, stop, and step size, and use linspace when you need a specific number of points evenly spaced within an interval.
# But both can do the same thing, its just preference
np_array = np.linspace(10,20,11)
print(np_array)

# Iterating over the array
for i in np_array:
    print(i)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0


In [10]:
np_matrix_ones = np.ones([3,5])          # 3 row and 5 column matrix with all ones
np_matrix_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np_matrix_zeroes = np.zeros([2,4])          # 2 row and 4 column matrix with all zeroes
np_matrix_zeroes



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
np_matrix_zeroes = np.zeros([2,4], dtype=int)          # 2 row and 4 column matrix with all zeroes and type integer
np_matrix_zeroes

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
#  np.eye returns only the square matrix
np_idendity_matrix = np.eye(5)      # idendity Matrix of 5X5. It has all diagonals as one.
np_idendity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr = np.arange(0,10)                    # Reshaped a linear list of data to 2X5 Matrix
arr_reshape = arr.reshape(2,5)
print(arr_reshape)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
## Trigonometric functions
print(np.sin(0.523599))           # 0.523599 radian is 30 degree
print(np.cos(0.523599))
print(np.tan(0.523599))
print(np.pi/2)

0.5000001943375613
0.8660252915835662
0.5773505683919328
1.5707963267948966


In [17]:
print(np.exp(2))         # this is equal to (e**2)       
print(np.log(2))         # Log of 2 with base e.
print(np.log10(100))     # Log 100 with base 2
#  The number e, also known as Euler's number, is a mathematical constant approximately equal to 2.71828 
#  that can be characterized in many ways. It is the base ...
array = np.array([2,4,6])
print(np.exp(array))           # This will print e**2, e**4, e**6

7.38905609893065
0.6931471805599453
2.0
[  7.3890561   54.59815003 403.42879349]


In [18]:
# Normal Matrix multiplication and addition are performed column wise

arr1 = np.arange(1,11).reshape(2,5)
print(arr1)
arr2 = np.arange(12,22).reshape(2,5)
print(arr2)
print(arr1+arr2)         # Operations are columnwise of matrix
print(arr1*arr2)         # Operations are columnwise of matrix
print(arr1-arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[12 13 14 15 16]
 [17 18 19 20 21]]
[[13 15 17 19 21]
 [23 25 27 29 31]]
[[ 12  26  42  60  80]
 [102 126 152 180 210]]
[[-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]]


In [20]:
##### Linear algebra Matrix multiplication

arr1 = np.arange(1,11).reshape(2,5)
print(arr1)
arr2 = np.arange(12,27).reshape(5,3)
print(arr2)
print("---------------------")
print(arr1 @ arr2)                 ## This will do the actual matrix dot mult

# Transpose a matrix. Flip rows to columns

arr1 = np.arange(0,12).reshape(3,4)
print(arr1)
print(np.transpose(arr1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]]
---------------------
[[300 315 330]
 [750 790 830]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [21]:
# We can do transpose in another way as
print(arr1.T)  ## Shirt hand notation of Matrix transpose

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [22]:
# min and Maximum in a numpy
arr1 = np.arange(0,12).reshape(3,4)
print(arr1)
print(np.min(arr1))
print(np.max(arr1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
11


In [24]:
# Random Value generations
print(np.random.rand(5)) # Create a single dimensional array of 5 elements with random values between 0 - 1 
print(np.random.rand(5,5))  # Create a 5X5 matrix of random number with values from 0 - 1

# randn creates a random number whose samples are drawn from normal distribution(Whose mean is 0 and standard deviation as 1)
arr1 = np.random.randn(5)
arr2 = np.random.randn(5,5) # Same as above but genarated 5X5 
print(arr1)
print(arr2)
print(np.mean(arr1))            #   Mean would be closer to 0
print(np.std(arr1))             #   Standard deviation would be 1

# Creates a 10 random number between 1 and 5(not including 5)
print(np.random.randint(1, 5, 10))  # low, high, number of random numbers.


[0.05472145 0.45889411 0.06816261 0.93924348 0.61564499]
[[0.51665582 0.9719442  0.31055625 0.37807853 0.66865533]
 [0.10752314 0.41818911 0.2616502  0.18183353 0.95092091]
 [0.77048597 0.03301444 0.23613081 0.38084529 0.21484267]
 [0.09617305 0.19300206 0.74553647 0.89715079 0.17316256]
 [0.38858115 0.37297499 0.87199938 0.28597559 0.60467773]]
[-0.39757766 -1.40633157 -0.41752409  0.72606848  0.56175011]
[[-0.13586318 -0.36648819  0.24206068  0.39656847  1.61734617]
 [ 1.08246345 -0.17736113 -0.83294001  0.80560527  1.96656411]
 [ 0.79183575 -0.29660975  1.6081789  -0.82885368 -0.63637439]
 [ 0.13923293  2.70014039  0.33209147  0.13663629  0.51699595]
 [-1.64154155 -0.58379265  0.38668871 -1.54780113  0.91962414]]
-0.18672294607411072
0.7718256477309448
[2 2 3 3 1 3 3 1 3 1]


In [25]:
# Accessing elements from the np array

print(np.arange(3, 10, 2))      # Range of numbers from 3-10 and step size of 2. The indices are 3,5,7,9
indices = np.arange(3, 10, 2)   # The indices are 3,5,7,9 
# Now let suppose we have a numpy array
arr1 = np.random.randn(50)
print(arr1[indices]) # Since indices are 3,5,7,9 so from arr1 get the values located at indices 3,5,7,9


[3 5 7 9]
[ 0.27422833 -0.4660131  -0.20510835 -2.41823636]


In [26]:
# Choosing the elements of array based on certain condition
arr = np.random.randn(50)
print(arr)
# Now let suppose we want only those elemnts which are greater than 0 in array arr then we can say
print(arr[arr>0])        # Filter data which are greater than Zero
# Similarly for numbers less than zero we can say
print(arr[arr<0])       # Filter data which are lesser than Zero  

[ 0.62436518 -0.84619007 -0.32874376 -1.06862471 -0.31047806 -1.7026289
  0.29262578  0.86223621 -1.91752405  0.38161524 -0.8190149   0.10043036
  1.30974454 -1.04855835  1.84244893 -0.91169803  0.58599228  0.85713519
 -1.79100047 -0.78048969  0.27860837  0.44500225 -2.04265809 -0.0681468
 -0.00839466 -0.90755025  0.52891544  1.96355822 -1.42127565  0.62241283
  0.576798   -0.59098982 -0.18666469 -0.24511414 -1.11446403 -1.21271337
 -0.12914449 -1.5922746   0.10864379  0.02426259  0.74970288 -0.0527003
 -1.18902698  0.12158786 -0.14224912  1.627082    0.01885257 -0.15322991
 -0.50068429 -0.44106767]
[0.62436518 0.29262578 0.86223621 0.38161524 0.10043036 1.30974454
 1.84244893 0.58599228 0.85713519 0.27860837 0.44500225 0.52891544
 1.96355822 0.62241283 0.576798   0.10864379 0.02426259 0.74970288
 0.12158786 1.627082   0.01885257]
[-0.84619007 -0.32874376 -1.06862471 -0.31047806 -1.7026289  -1.91752405
 -0.8190149  -1.04855835 -0.91169803 -1.79100047 -0.78048969 -2.04265809
 -0.0681468

In [28]:
# Below code would replace all elements greater than 6 with 2, remainder of the element in array will remain as it is
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


In [29]:
arr = np.random.randint(0, 50, 20)    # Low, high, number of random number
print(arr)
new_arr = arr.reshape((5,4))
print(new_arr)

# Now in order to access a specific element let suppose  2nd row and 3rd element we can say
print(new_arr[1,2])          # We can access in this way the element at indices 1 and 2 and also as shotcut in below
print(new_arr[1][2])    

print(new_arr[1])           # Print all the elements of row index 1

new_arr[1:3, 0:2] = -100       # Changes the elements from "row 1 till 2(Not including 3)" and from column 0 till 
print(new_arr)

new_arr[:] = 0
print(new_arr)         # Change all rows and columns to 0

[48  9 39 12 47 28  5 48  3 29  2 44 11 48 31 47 43 29 20 21]
[[48  9 39 12]
 [47 28  5 48]
 [ 3 29  2 44]
 [11 48 31 47]
 [43 29 20 21]]
5
5
[47 28  5 48]
[[  48    9   39   12]
 [-100 -100    5   48]
 [-100 -100    2   44]
 [  11   48   31   47]
 [  43   29   20   21]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [30]:
# Copy method to create a new copy of array instead of reference to original array

arr = np.random.randint(0, 50, 20).reshape(5,4)    # Low, high, number of random number
print(arr)
sub_array = arr[2,0:3]
print(sub_array)
sub_array[:] = 0 
print(sub_array)
print(arr)            # Note original array also got modified with zeroes for 3rd row and 0-3 columns


[[ 8 23  3 22]
 [40 26 43 17]
 [13 42 42 23]
 [36  0 38 11]
 [29  8 17 31]]
[13 42 42]
[0 0 0]
[[ 8 23  3 22]
 [40 26 43 17]
 [ 0  0  0 23]
 [36  0 38 11]
 [29  8 17 31]]


In [31]:
# If we dont want reference or tie up between original array and new subarray we can use copy method

arr = np.random.randint(0, 50, 20).reshape(5,4)    # Low, high, number of random number
sub_array = arr[2,0:3].copy()
print(sub_array)
sub_array[:] = 0 
print(sub_array)
print(arr)            # Note original array also got modified with zeroes for 3rd row and 0-3 columns


[27 35 42]
[0 0 0]
[[ 6 34 39 29]
 [46 40 24 18]
 [27 35 42 41]
 [30 46 42 19]
 [32 14 14 23]]


In [32]:
##########################################################
# saving the np data
arr = np.arange(15,25).reshape(5,2)
print(arr)
np.save("np_saved_data", arr)
loaded_arr = np.load("./np_saved_data.npy")
print(loaded_arr)

[[15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
[[15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]


In [33]:
# saving multiple data in one file using np.savez
# and loading multiple arrays back from file
arr1 = np.arange(15,25).reshape(5,2) 
arr2 = np.arange(25,35).reshape(2,5) 
np.savez("np_saved_ez", arr1, arr2)
loaded_array = np.load("np_saved_ez.npz")
arr_1 = np.load("np_saved_ez.npz")
print(loaded_array["arr_0"])
print(loaded_array["arr_1"])

[[15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
[[25 26 27 28 29]
 [30 31 32 33 34]]


In [34]:
# Saving and loading the numpy array in a textfile and loading it back
arr1 = np.arange(15,25, dtype = int).reshape(5,2) 
np.savetxt("np_save.txt", arr1, delimiter=",")
arr1 = np.loadtxt("np_save.txt", delimiter = ",", dtype=int)
print(arr1)

[[15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]


/var/folders/xv/mx7fpfds1nb2h2ps9fxzf1180000gn/T/ipykernel_4222/3594553886.py:4: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  arr1 = np.loadtxt("np_save.txt", delimiter = ",", dtype=int)


In [35]:

a1 = np.arange(10)
print(a1) 
print(a1.shape)

print('------------')
## Provide the step size of 2
a2 = np.arange(0,11,2)      ##2,2,4,6,8,10
print(a2) 
print(a2.shape)             ##

a3 = np.zeros(5)
print(a3)
print(a3.shape)


print('---------------------')
a4 = np.zeros((5,4))    # Two dimensional array with 5 rows and 4 columns
print(a4)
print(a4.shape)


print('---------------------')
a5 = np.full((5,4),8)    # Two dimensional array with 5 rows and 4 columns and filled with all 8
print(a5)
print(a5.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
------------
[ 0  2  4  6  8 10]
(6,)
[0. 0. 0. 0. 0.]
(5,)
---------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(5, 4)
---------------------
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
(5, 4)


In [36]:

###Identity Matrix
print("-------------------")
a6 = np.eye(4)  # Creates an identity matrix of 4X4 with all diagoanal element as 1
print(a6)


-------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:

## Array filled with random number
print("-------------------")
a7 = np.random.random((2,4))
print(a7)

# Create a numpy array from python list
list1 = [1,2,3,4,5]
r1 = np.array(list1)
print(r1)


## Creating and accessing a two dimensional array
print('------------------')
#a4 = np.zeros((5,4))    # Two dimensional array with 5 rows and 4 columns

-------------------
[[0.80154653 0.79212928 0.31239958 0.36932365]
 [0.93746759 0.26255098 0.2654385  0.40730722]]
[1 2 3 4 5]
------------------


In [38]:
a4 = np.random.random((5,4) )    # Two dimensional array with 5 rows and 4 columns

print(a4)
print(a4.shape)

print('------------------')
for x in range(len(a4)):
    print(a4[x])

print(a4[2][0])
print(a4[2][1])

[[9.13629268e-01 1.15057666e-01 8.64482398e-01 6.92712695e-01]
 [8.88632558e-01 1.44331271e-04 7.26303572e-01 3.23592486e-01]
 [7.09662438e-01 1.07319733e-01 1.79296971e-01 1.95758600e-01]
 [5.44913554e-01 6.73111385e-01 8.67612352e-01 8.87528847e-01]
 [9.50508386e-01 9.67719536e-02 4.36562248e-02 5.61017257e-01]]
(5, 4)
------------------
[0.91362927 0.11505767 0.8644824  0.6927127 ]
[8.88632558e-01 1.44331271e-04 7.26303572e-01 3.23592486e-01]
[0.70966244 0.10731973 0.17929697 0.1957586 ]
[0.54491355 0.67311139 0.86761235 0.88752885]
[0.95050839 0.09677195 0.04365622 0.56101726]
0.7096624376617939
0.10731973297383202


In [40]:
### print odd number using boolen indexing in numpy
import numpy as np
import time

a = np.arange(10)
print(a%2 == 1)
odd_num = a[a%2 == 1]
print(odd_num)


def p(*args):
    print("############################")
    for arg in args:
        print(arg)

print(np.sin(0.523599))

print(np.sin(np.array([30,60,120,180])))

[False  True False  True False  True False  True False  True]
[1 3 5 7 9]
0.5000001943375613
[-0.98803162 -0.30481062  0.58061118 -0.80115264]


In [41]:
x1 = np.array([1,2,3,4])
print(x1[1])

2


In [42]:
x2 = np.array([4,3,1,2], dtype=np.int32)
print(x1.dtype)
print(x2.dtype)


int64
int32


In [43]:
print(x1*x2)  # Array of element wise multiplication  1*4, 2*3, 3*1, 4*2


[4 6 3 8]


In [44]:
# Create a random element in numpy

r1= np.random.rand(1_000_000)
r2= np.random.rand(1_000_000)

start = time.time()
x = r1 * r2
end = time.time()
print(end-start)


0.0009140968322753906


In [45]:
x1 = np.array([1,2,3,4])
x2 = np.array([[4],[3],[1],[2]])

print(x1 @ x2) # Scientific dot product of matrix
# 1*4 + 2*3 + 3*1 + 4*2 = 21


[21]


In [46]:
# get a range of array similar to python range
x = np.arange(12)
print(x)            # Get a number from range 0 -12(not including 12)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [47]:
# Reshap an array 

x = x.reshape(4,3)          # Shape it to 4 rows and 3 columns
print(x)
print(x.shape)              # Tells the shape of the Matrix, like 4,3 etc

print(x.T)                  # Prints the transformed matrix, ROWs becomes column.

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [48]:
x= np.array([[1,2,3],[5,6,7],[3,6,-1]])
print(x)

# [[ 1  2  3]
#  [ 5  6  7]
#  [ 3  6 -1]]

# If we need to get from second row and third element we can say
print(x[1,2])      # this will print 7

# If we need all element of 3rd row
print(x[2,:])         # This will print 3, 6, -1

# If we all all element of 2nd columns of all row we can say
print(x[:, 1])  # This will print 2, 6, 6


[[ 1  2  3]
 [ 5  6  7]
 [ 3  6 -1]]
7
[ 3  6 -1]
[2 6 6]


In [49]:
# Intialize or fill an array with Another value

x = np.arange(3)
p(x)

x = x[[True, False, True]]
p(x)         # This will print the element where index was true like 0 2 in this case

x =np.array([1,0,-2,5,25,0,-3]) 
p(x[x>=1])       # Gets the lcaotion of the array where it is greater than 1
                # 1,5,25

############################
[0 1 2]
############################
[0 2]
############################
[ 1  5 25]


In [50]:
arr = np.arange(10)
print(arr)
p(arr[(arr>7) |  (arr <2)])        # 0 1 8 9, prints an array 0 1 8 9
                                    # Note we have to provide condition in bracket()

p(arr[~(arr>7)])    # Print everything not greater than 7 [0,1,2,3,4,5,6,7]

[0 1 2 3 4 5 6 7 8 9]
############################
[0 1 8 9]
############################
[0 1 2 3 4 5 6 7]


In [51]:
# Create an array of 10 elements with values filled as 1000

values = np.random.normal(0,10, 1_000)       # Array of 1000 elements with mean of 0 and standard deviation of 10
values[33] = 1038                   
values[832] = -3423
p(values)
p(values.mean())

mask = np.abs(values - values.mean()) > (2* values.std())
print(values[mask])                             # This will give the values of outlier, basically values[33] and values[832]


############################
[ 9.68090694e+00 -4.80296701e+00 -1.30936992e+01  8.63941917e+00
  1.59643173e+00 -1.20640070e+01 -3.93873159e+00 -1.88892949e+00
  4.26762941e+00  6.33899022e-01 -5.02489629e+00 -4.36237049e+00
 -1.53902180e+00 -2.58051984e+01  5.55720994e+00 -1.36165370e+01
 -1.40006298e+00  1.51369536e+00 -1.12496936e+01  1.16392597e+00
  6.14218466e+00  2.01848867e+01  4.16946835e+00 -1.52186494e+00
 -5.21012940e+00  1.15567123e+01 -1.83302438e+00  5.81605016e+00
  7.44173701e+00 -2.78889024e+00  8.84573419e+00 -7.56045103e+00
 -8.63410005e+00  1.03800000e+03  4.08840102e-01  1.22720302e+01
  1.38840031e+00 -3.19816363e+00 -1.81544878e+01 -1.12766327e+01
  5.26293195e+00  2.59896530e+01  1.46790701e+00 -6.60962747e+00
 -1.08136863e+01 -4.23421465e+00 -1.68502945e+01 -9.42478748e+00
 -2.26704165e+01  1.58994115e+01 -4.65007812e+00  7.15265340e+00
  2.78806115e+00  1.43966002e+01  1.57019460e+01 -1.19140141e+01
 -7.05028012e+00 -3.39445530e+00  8.59302492e+00  1.10097570e

In [52]:
arr = np.arange(3)
p(arr)
p(arr+4)       # Added the 4 to each of the elements



############################
[0 1 2]
############################
[4 5 6]


In [53]:
# Broadcasting 1

mat = np.arange(9).reshape((3,3))
vec = np.arange(3)
p(mat)
p(vec)
p(mat+vec)      # Added the vector to every row

############################
[[0 1 2]
 [3 4 5]
 [6 7 8]]
############################
[0 1 2]
############################
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [54]:
# Broadcasting 2

v1 = np.arange(3)
v2 = np.arange(3).reshape((3,1))
p(v1)
p(v2)
p(v1+v2)             ## Added the vector v1 to each row of v2

############################
[0 1 2]
############################
[[0]
 [1]
 [2]]
############################
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [55]:
v = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]
              ])
p("Original vector is ", v)
p(v.T)    # T is for trnaspose Matrix, the rows would become the colums

p(v.any())         # This will return true if there is atleast one element in the array which is true

p(v.all())          #v.all will return True if all elements of matrix is true, else it returns false


############################
Original vector is 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
############################
[[0 3 6]
 [1 4 7]
 [2 5 8]]
############################
True
############################
False


In [56]:
v = np.array([[1,1,2],
              [3,4,5],
              ])
p(v.prod())              # Product of all the elements in an array

p(v.sum(axis=1))       # Sum of the rows
p(v.sum(axis=0))       # Sum of the colums



############################
120
############################
[ 4 12]
############################
[4 5 7]


In [57]:
v1 = np.array([[1,1,2],
              [3,4,5],
              ])
v2 = v1.copy()   # Creates a copy of the original array
v2[1,2] = 16
p(v1)
p(v2)


############################
[[1 1 2]
 [3 4 5]]
############################
[[ 1  1  2]
 [ 3  4 16]]


In [58]:
x = np.sin(90)  # This 90 is in radian not degree
p(x)


############################
0.8939966636005579


In [62]:
n = np.arange(-3,3)     # Run the sine function on a vector
print(np.sin(v))


[[ 0.84147098  0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]]
############################
[[ 0.84147098  0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]]


In [63]:
@np.vectorize                 #This method would make the data extend to vector
def relu(n):
    if n<0:
        return 0.0
    return n

p(relu(2))

v1 = np.arange(-3,5)
p(v1)

p(relu(v1))
p(relu(v1)-7)         # This will remove -7 from vector(i.e, each component of the vector)


############################
2
############################
[-3 -2 -1  0  1  2  3  4]
############################
[0. 0. 0. 0. 1. 2. 3. 4.]
############################
[-7. -7. -7. -7. -6. -5. -4. -3.]


In [64]:

#Pearson Correlation

def correlation_coefficient(data1, data2):
  """
  Calculates the correlation coefficient between two lists of data.

  Args:
    data1: The first list of data.
    data2: The second list of data.

  Returns:
    The correlation coefficient between the two lists of data.
  """

  mean1 = np.mean(data1)
  mean2 = np.mean(data2)
  std1 = np.std(data1)
  std2 = np.std(data2)

  covariance = np.sum((data1 - mean1)*(data2 - mean2)) / len(data1)
  correlation = covariance / (std1 * std2)

  return correlation