In [5]:
!pip install gensim

In [6]:
import gensim.downloader as api
import numpy as np
model = api.load("word2vec-google-news-300")

In [7]:
word_vectors = model
print(len(word_vectors['computer']))
print((word_vectors['computer'].shape))
print((word_vectors['computer']))

300
(300,)
[ 1.07421875e-01 -2.01171875e-01  1.23046875e-01  2.11914062e-01
 -9.13085938e-02  2.16796875e-01 -1.31835938e-01  8.30078125e-02
  2.02148438e-01  4.78515625e-02  3.66210938e-02 -2.45361328e-02
  2.39257812e-02 -1.60156250e-01 -2.61230469e-02  9.71679688e-02
 -6.34765625e-02  1.84570312e-01  1.70898438e-01 -1.63085938e-01
 -1.09375000e-01  1.49414062e-01 -4.65393066e-04  9.61914062e-02
  1.68945312e-01  2.60925293e-03  8.93554688e-02  6.49414062e-02
  3.56445312e-02 -6.93359375e-02 -1.46484375e-01 -1.21093750e-01
 -2.27539062e-01  2.45361328e-02 -1.24511719e-01 -3.18359375e-01
 -2.20703125e-01  1.30859375e-01  3.66210938e-02 -3.63769531e-02
 -1.13281250e-01  1.95312500e-01  9.76562500e-02  1.26953125e-01
  6.59179688e-02  6.93359375e-02  1.02539062e-02  1.75781250e-01
 -1.68945312e-01  1.21307373e-03 -2.98828125e-01 -1.15234375e-01
  5.66406250e-02 -1.77734375e-01 -2.08984375e-01  1.76757812e-01
  2.38037109e-02 -2.57812500e-01 -4.46777344e-02  1.88476562e-01
  5.51757812e-

In [8]:
word_vectors.most_similar(positive=['king','woman'], negative=['man'])

[('queen', 0.7118192911148071),
 ('monarch', 0.6189674735069275),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321243286133),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134343147278),
 ('sultan', 0.5098593235015869),
 ('monarchy', 0.5087411999702454)]

In [9]:
print(word_vectors.similarity('woman','man'))
print(word_vectors.similarity('king','queen'))
print(word_vectors.similarity('boy','girl'))
print(word_vectors.similarity('monkey','banana'))
print(word_vectors.similarity('chimpanzee','banana'))
print(word_vectors.similarity('lion','banana'))


0.76640123
0.6510956
0.8543272
0.32453138
0.15475729
0.12956943


In [10]:
print(word_vectors.most_similar("tower", topn=5))

[('towers', 0.8531749844551086), ('skyscraper', 0.641742467880249), ('Tower', 0.639177143573761), ('spire', 0.5946878790855408), ('responded_Understood_Atlasjet', 0.5931612849235535)]


In [11]:
vector_difference = word_vectors['king'] - word_vectors['man']
magnitude = np.linalg.norm(vector_difference)
print("Magnitude of the difference vector between 'king' and 'man':", magnitude)

Magnitude of the difference vector between 'king' and 'man': 3.2687893


In [12]:
vector_difference = word_vectors['semiconductor'] - word_vectors['earthworm']
magnitude = np.linalg.norm(vector_difference)
print("Magnitude of the difference vector between 'king' and 'man':", magnitude)

Magnitude of the difference vector between 'king' and 'man': 5.6670427


In [20]:
#creation of my own embeddings

In [13]:
import torch

In [19]:
input_ids = torch.tensor([2,3,5,1])
print(input_ids)                        

tensor([2, 3, 5, 1])


In [22]:
vocan_size = 6
output_dim = 3
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocan_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [25]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [26]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
